version: '3.4'
services:
    workoutservice:
        ports:
            - '4300:80'
        volumes:
            - './configpath/workoutservice/docker/logs:/logs'
            - './configpath/workoutservice/docker/configfiles:/settings'
        environment:
            - nlogdirectory=/settings/
            - appdirectory=/settings/
    dietservice:
        ports:
            - '4301:80'
        volumes:
            - './configpath/dietservice/docker/logs:/logs'
            - './configpath/dietservice/docker/configfiles:/settings'
        environment:
            - nlogdirectory=/settings/
            - appdirectory=/settings/   
    webstatus:
        ports:
            - '4303:80'
        volumes:
            - './configpath/webstatus/docker/logs:/logs'
            - './configpath/webstatus/docker/configfiles:/settings'
        environment:
            - nlogdirectory=/settings/
            - appdirectory=/settings/
    fitnesstracker:
        ports:
            - '4304:80'
        volumes:
            - './configpath/fitnesstracker/docker/logs:/logs'
            - './configpath/fitnesstracker/dist:/dist'
        environment:
            - dist=/dist

    workouthub:
        ports:
            - '4305:80'
        volumes:
            - './configpath/workouthub/docker/logs:/logs'
            - './configpath/workouthub/docker/configfiles:/settings'
        environment:
            - nlogdirectory=/settings/
            - appdirectory=/settings/
    diethub:
        ports:
            - '4306:80'
        volumes:
            - './configpath/diethub/docker/logs:/logs'
            - './configpath/diethub/docker/configfiles:/settings'
        environment:
            - nlogdirectory=/settings/
            - appdirectory=/settings/