version: '3.4'
services:
    workoutservice:
        ports:
            - '4300:80'
        volumes:
            - './configpath/workoutservice/logs:/logs'
            - './configpath/workoutservice/configfiles:/settings'
        environment:
            - nlogdirectory=/settings/
            - appdirectory=/settings/
    dietservice:
        ports:
            - '4301:80'
        volumes:
            - './configpath/dietservice/logs:/logs'
            - './configpath/dietservice/configfiles:/settings'
    signalrhub:
        ports:
            - '4302:80'
        volumes:
            - './configpath/signalrhub/logs:/logs'
            - './configpath/signalrhub/configfiles:/settings'
    webstatus:
        ports:
            - '4303:80'
        volumes:
            - './configpath/webstatus/logs:/logs'
            - './configpath/webstatus/configfiles:/settings'
    fitnesstracker:
        ports:
            - '4304:80'
        volumes:
            - './configpath/fitnesstracker/logs:/logs'
            - './configpath/fitnesstracker/dist:/dist'