version: '3.4'
services:
    workoutservice:
        image: 'workoutservice:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Workout.Service/Dockerfile
    dietservice:
        image: 'dietservice:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Diet.Service/Dockerfile
    webstatus:
        image: 'webstatus:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Presentation.WebStatus/Dockerfile
    fitnesstracker:
        image: 'fitnesstracker:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Presentation.Angular/Dockerfile
        depends_on:
            - workoutservice
            - dietservice
    workouthub:
        image: 'workouthub:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Presentation.Workout.MessageHub/Dockerfile
    diethub:
        image: 'diethub:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Presentation.Diet.MessageHub/Dockerfile