version: '3.4'
services:
    workoutservice:
        image: 'workoutservice:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Workout.Service/Dockerfile
    dietservice:
        image: 'dietservice:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Diet.Service/Dockerfile
    signalrhub:
        image: 'signalrhub:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Presentation.SignalRHub/Dockerfile

    webstatus:
        image: 'webstatus:${TAG:-latest}'
        build:
            context: .
            dockerfile: FitnessTracker.Presentation.WebStatus/Dockerfile