apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "charts.name" . }}
    helm.sh/chart: {{ include "charts.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "charts.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "charts.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: "appdirectory"
              value: "/app/settings/"
            - name: "nlogdirectory"
              value: "/app/settings/"
          volumeMounts:
            - name: configs
              mountPath: "/app/settings"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http       
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-workout
              - configMap:
                  name: log-config
              - secret:
                  name: appsettings-secret-workout